/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResRouteImport } from './routes/res'
import { Route as MouseLockRouteImport } from './routes/mouse-lock'
import { Route as ManualRouteImport } from './routes/manual'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResRoute = ResRouteImport.update({
  id: '/res',
  path: '/res',
  getParentRoute: () => rootRouteImport,
} as any)
const MouseLockRoute = MouseLockRouteImport.update({
  id: '/mouse-lock',
  path: '/mouse-lock',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualRoute = ManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/manual': typeof ManualRoute
  '/mouse-lock': typeof MouseLockRoute
  '/res': typeof ResRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/manual': typeof ManualRoute
  '/mouse-lock': typeof MouseLockRoute
  '/res': typeof ResRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/manual': typeof ManualRoute
  '/mouse-lock': typeof MouseLockRoute
  '/res': typeof ResRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/manual' | '/mouse-lock' | '/res' | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/manual' | '/mouse-lock' | '/res' | '/settings'
  id: '__root__' | '/' | '/manual' | '/mouse-lock' | '/res' | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ManualRoute: typeof ManualRoute
  MouseLockRoute: typeof MouseLockRoute
  ResRoute: typeof ResRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/res': {
      id: '/res'
      path: '/res'
      fullPath: '/res'
      preLoaderRoute: typeof ResRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mouse-lock': {
      id: '/mouse-lock'
      path: '/mouse-lock'
      fullPath: '/mouse-lock'
      preLoaderRoute: typeof MouseLockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual': {
      id: '/manual'
      path: '/manual'
      fullPath: '/manual'
      preLoaderRoute: typeof ManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ManualRoute: ManualRoute,
  MouseLockRoute: MouseLockRoute,
  ResRoute: ResRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
